### ISSUE TITLE
Explain why an installation of `esperanto-cosmopolitan` can fail on a Linux system

### ISSUE THREAD

**Issue by dinosaure** [dinosaure/esperanto#26]
Currently, a Linux system with `binfmt_misc` + Wine can not install `esperanto-cosmopolitan` because we use an APE program to extract the Cosmopolitan archive. In such situation, the installation fail because `binfmt_misc` recognizes our `extract.com` as a Wine program. We should, at least, warn the user and explain to him/her to follow these instructions: https://justine.lol/apeloader/#binfmt_misc (which needs root privilege).

Moreover, we probably should not use an APE program to _unzip_ the Cosmopolitan archive.

**Comment by jart** [comment]
You can vendor https://justine.lol/ape.elf and https://justine.lol/ape.macho if you need a solution for making sure the binfmt_misc workaround always works.

**Comment by dinosaure** [comment]
Currently, we decided to warn the OPAM user and give to him/her the explanation and a link to your website. It was done by the `conf-cosmopolitan` package.
